version: '3.9'
services:
  # nginx:
  #   context: .
  #   ports:
  #     - 80:80
  #   volumes:
  #     - .default.conf:/etc/nginx/conf.d/default.conf

  #   depends_on:
  #     - lannister-frontend

  lannister-frontend:
    image: lannister-frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/:/app/
    ports:
      - 8000:8000
    depends_on:
      - postgresdb

  lannister-backend:
    image: lannister-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/:/app/
    ports:
      - 8001:8001
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=demigorrgon
      - POSTGRES_PASSWORD=somepass1
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
