version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - lannister-frontend

  lannister-frontend:
    image: lannister-frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app/
    ports:
      - 8000:8000
    environment:
      - BOT_USER_OAUTH_TOKEN=${BOT_USER_OAUTH_TOKEN}

  lannister-backend:
    image: lannister-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app/
    ports:
      - 8001:8001
    depends_on:
      - postgresdb
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=postgresdb
      - DB_NAME=${DB_NAME}
      - POSTGRES_USER=demigorrgon
      - POSTGRES_PASSWORD=somepass1

  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: demigorrgon
      POSTGRES_PASSWORD: somepass1
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
