version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - lannister-frontend

  lannister-frontend:
    image: ${FRONTEND_DOCKER_IMAGE}
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgresdb
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - SIGNING_SECRET=${SIGNING_SECRET}
      - BOT_USER_OAUTH_TOKEN=${BOT_USER_OAUTH_TOKEN}
    volumes:
       - /home/ubuntu/frontend_vol:/app/
    ports:
      - 8000:8000
    depends_on:
      postgresdb:
        condition: service_healthy

  lannister-backend:
    image: ${BACKEND_DOCKER_IMAGE}
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=postgresdb
    volumes:
      - /home/ubuntu/backend_vol:/app/
    ports:
      - 8001:8001
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
