# Generated by Django 3.2 on 2022-07-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusrequest',
            name='bonus_type',
            field=models.CharField(choices=[('Referral', 'Referral'), ('Overtime', 'Overtime')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bonusrequest',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Created', max_length=50),
        ),
    ]
