# Generated by Django 3.2 on 2022-07-09 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusrequestshistory',
            options={'ordering': ('-bonus_request__updated_at',), 'verbose_name_plural': 'Bonus requests history'},
        ),
        migrations.AddField(
            model_name='bonusrequestshistory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
