# Generated by Django 3.2 on 2022-07-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_slack', '0002_auto_20220709_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusrequestshistory',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'Bonus requests history'},
        ),
        migrations.AddField(
            model_name='bonusrequestshistory',
            name='status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='lannister_slack.bonusrequeststatus'),
            preserve_default=False,
        ),
    ]
