# Generated by Django 3.2 on 2022-07-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_slack', '0003_auto_20220709_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusrequest',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bonusrequestshistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lannister_slack.bonusrequeststatus'),
        ),
    ]
