# Generated by Django 3.2 on 2022-07-04 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_slack', '0003_auto_20220704_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusrequestshistory',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bonusrequestshistory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_statuses', to='lannister_slack.bonusrequeststatus'),
        ),
    ]
