# Generated by Django 3.2 on 2022-07-28 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('Referral', 'Referral'), ('Overtime', 'Overtime')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bonus_requests',
            },
        ),
        migrations.CreateModel(
            name='BonusRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Bonus status',
                'verbose_name_plural': 'Bonus statuses',
                'db_table': 'bonus_requests_status',
            },
        ),
        migrations.CreateModel(
            name='BonusRequestsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(null=True)),
                ('bonus_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_requests', to='lannister_requests.bonusrequest')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_statuses', to='lannister_requests.bonusrequeststatus')),
            ],
            options={
                'verbose_name_plural': 'Bonus requests history',
                'db_table': 'bonus_requests_history',
            },
        ),
        migrations.AddField(
            model_name='bonusrequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='lannister_requests.bonusrequeststatus'),
        ),
    ]
