# Generated by Django 3.2 on 2022-07-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonusrequestshistory',
            old_name='date',
            new_name='updated_at',
        ),
    ]
