# Generated by Django 3.2 on 2022-07-28 22:04

from django.db import migrations, models
import django.db.models.deletion
import lannister_requests.models


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusrequest',
            name='status',
            field=models.ForeignKey(default=lannister_requests.models.set_request_status, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='lannister_requests.bonusrequeststatus'),
        ),
    ]
