# Generated by Django 3.2 on 2022-07-01 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lannisteruser',
            options={'ordering': ['id'], 'verbose_name': 'Lannister User', 'verbose_name_plural': 'Lannister Users'},
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
