# Generated by Django 3.2 on 2022-07-28 22:04

from django.db import migrations, models
import lannister_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_roles', '0001_initial'),
        ('lannister_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lannisteruser',
            name='roles',
            field=models.ManyToManyField(default=lannister_auth.models.set_user_role, to='lannister_roles.Role'),
        ),
    ]
