# Generated by Django 3.2 on 2022-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_roles', '0001_initial'),
        ('lannister_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lannisteruser',
            name='roles',
            field=models.ManyToManyField(to='lannister_roles.Role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
