# Generated by Django 3.2 on 2022-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lannister_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lannisteruser',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
